### ISSUE TITLE
scOT.models import not working

### ISSUE THREAD

**Issue by visujadhav** [camlab-ethz/poseidon#1]
After installation from git, and running following code

`from scOT.models import ScOT

model = ScOT.from_pretrained("camlab-ethz/Poseidon-<MODEL_SIZE>")`

I am getting error as follows:
ModuleNotFoundError: No module named 'scOT.models'

Please advise about the potential solution for this case.

**Comment by visujadhav** [comment]
Just found the solution:
replaced `from scOT.models import ScOT`
with `from scOT.model import ScOT`

Request authors to update the README file.

**Comment by maximilianherde** [comment]
Thanks a lot for pointing this out. I just fixed it in the README.
