### ISSUE TITLE
Restarting and continuing the training

### ISSUE THREAD

**Issue by smao-astro** [camlab-ethz/poseidon#10]
Dear developers,

Thank you very much for publishing the code. I am new to it. May I ask if is there an easy way to continue the model pertaining with a restart, after the training is terminated by, for example, an HPC job scheduler. 

Thanks again.

**Comment by maximilianherde** [comment]
Yes, this should be possible. Set `--finetune_from` to the directory with your checkpoint (as you would for finetuning) and set `--resume_training`.
