### ISSUE TITLE
Transformers package pinned in pyproject.toml is incompatible with training script

### ISSUE THREAD

**Issue by fsherry** [camlab-ethz/poseidon#3]
Thank you for providing access to your code for this project. I am eager to give it a try, by fine-tuning on some PDE tasks.
Following the instructions in the README, I am running into issues with the training script.
In particular, installing everything in a fresh environment, and running the training command (after including the fix in #2), I get this error:
```
Traceback (most recent call last):
  File "/mhome/maths/q/fs436/poseidon/scOT/train.py", line 277, in <module>
    train_config = TrainingArguments(
                   ^^^^^^^^^^^^^^^^^^
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'
```

Looking into it in more detail, it seems that the version of `transformers` (4.29.2) pinned in `pyproject.toml` is not compatible with the training script, as in that version `TrainingArguments` does not accept an argument `eval_strategy` (see https://github.com/huggingface/transformers/blob/v4.29.2/src/transformers/training_args.py). Could you please update the `transformers` dependency to fix this?

I can confirm that the script gets past this error after installing the latest version of `transformers` with `pip install -U transformers` (after removing the version pin in `pyproject.toml`).
The error that I get after that seems to be unrelated (`ValueError: Make sure that the channel dimension of the pixel values match with the one set in the configuration.`) and I assume that it can be fixed by me appropriately changing the config.

**Comment by maximilianherde** [comment]
Thanks a lot for pointing this out. I fixed the argument to be compatible with the version in pyproject.toml. In later versions, we will lift the dependency on this older version of `transformers`. I first need to check whether the subclassed Trainer works with newer versions of `transformers`.

For the latter error, if you are deriving your own dataset from `Base(Time)Dataset`, make sure to set `self.input_dim` to the corresponding number of input variables and set `self.label_description`; this will automatically set the output dimensions. For further information, please refer to [https://camlab-ethz.github.io/poseidon/](https://camlab-ethz.github.io/poseidon/).

**Comment by fsherry** [comment]
Thanks, that works for me! 

Regarding the second error I mentioned, I was actually trying with the Allen-Cahn data, but I wasn't using the flag `--replace_embedding_recovery`, which was what causing my error. It seems to be working now.
