### ISSUE TITLE
Checkpoints are deleted at end of fine-tuning run due to bug in transformers 4.29.2

### ISSUE THREAD

**Issue by fsherry** [camlab-ethz/poseidon#4]
I have successfully completed some fine-tuning runs with the commands listed in the README.

During these runs I saw model checkpoints being saved. To my surprise, after the runs completed, the checkpoints were deleted and there was no trace left of the best models.

It seems to be this issue in the `transformers` package: https://github.com/huggingface/transformers/issues/25129.
The issue was fixed and the fix seems to have been released in versions from 4.32.0 (i.e. in a later version than pinned in `pyproject.toml`: https://github.com/huggingface/transformers/commit/de9e3b59456a2a5607facbe4d160b5116062a912

There seem to be multiple ways of fixing this: updating `transformers` (which you mentioned you want to check first), or (maybe the easiest) adding a call to `trainer.save_model` after the `trainer.train` in https://github.com/camlab-ethz/poseidon/blob/main/scOT/train.py.

**Comment by fsherry** [comment]
I've implemented the second option in #5, but am open to whatever you decide :)

**Comment by maximilianherde** [comment]
I see -- for me it worked... Did you pass a relative path to `params.ckpt_dir`?

**Comment by fsherry** [comment]
No, this is with absolute paths. I don't know if that is meant to be better or worse for huggingface?

**Comment by maximilianherde** [comment]
I see...

I think I've found the problem. I suppose you are not using Weights & Biases? I just tried without W&B and this issue occurs (WANDB_MODE=disabled); if I allow W&B, it works -- output_dir gets a dummy name if W&B is disabled and somehow this breaks things

**Comment by fsherry** [comment]
I was using weights and biases, so I can see the directory structure `<ckpt_dir>/<wandb project name>/<wandb run name>` and looking inside during training I saw the checkpoints. After the training completes, when `trainer` tries to clean up the checkpoint directory, it deletes all of them. It seems to be an issue with older versions of `transformers`.

**Comment by maximilianherde** [comment]
I also tried now and get the same problem. That's very weird because it worked before, maybe because I was using slightly different code (but in this regard not different...) or it had to do with SLURM (all jobs I ran before were done using a batch system).

Thanks for pointing the problem out, I will accept your PR.

**Comment by fsherry** [comment]
Thank you! Is there any chance you were using a newer version of `transformers` before? I ask since that would be consistent with issue #3 as well.

**Comment by maximilianherde** [comment]
No, I checked again, but it was exactly version 4.29.2.
