### ISSUE TITLE
Calculation of variance in layer norm

### ISSUE THREAD

**Issue by cyhuangx** [camlab-ethz/poseidon#6]
I found the calculation of variance in layer norm wrong:
https://github.com/camlab-ethz/poseidon/blob/2cc8c85f61842ab35ca5e51634057928da88f96f/scOT/model.py#L152
which would cause the variance of the normalized features to not be 1.
Although I think the MLP may be able to learn to adjust $\alpha(t)$ to partly compensate for this.

**Comment by maximilianherde** [comment]
I don't understand what is wrong in this implementation. Could you elaborate on what is wrong and maybe propose a correct version?

What is implemented is the biased estimator of the variance as proposed in the original Layer Normalization paper, as far as I remember.

The variance is given by 
sigma^2 = E[(X-E[X])^2] = E[X^2] - E[X]^2 which is what is implemented.

**Comment by cyhuangx** [comment]
You're definitely right. Somehow I made a ridiculous mistake. Thank you for your patience.
